# 18th July 2026

In [5]:
%pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126
Note: you may need to restart the kernel to use updated packages.


In [6]:
import torch
import torchvision

print(torch.__version__)
print(torchvision.__version__)

2.13.0+cu126
0.28.0+cu126


In [7]:
data = [1,2,3,4]
print(type(data))
data=torch.tensor(data)
print(type(data))

<class 'list'>
<class 'torch.Tensor'>


In [8]:
torch.zeros((5,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.rand((5,3))

tensor([[0.5290, 0.9924, 0.7589],
        [0.3757, 0.4630, 0.1663],
        [0.9410, 0.9697, 0.9628],
        [0.4834, 0.5571, 0.7769],
        [0.3861, 0.1019, 0.0856]])

In [10]:
torch.randn((5,3))

tensor([[ 1.1538,  0.9661,  0.2439],
        [ 0.7706,  1.4813,  0.3355],
        [ 0.3739, -0.7105,  1.7621],
        [-0.2085,  0.7799,  0.8010],
        [ 0.1849, -0.6448,  0.5755]])

In [11]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
print (f"CUDA Available:{torch.cuda.is_available()}")
print (f"CUDA Device Count:{torch.cuda.device_count()}")
print(f"Device Name:{torch.cuda.get_device_name(0)}")

CUDA Available:True
CUDA Device Count:1
Device Name:NVIDIA GeForce RTX 4050 Laptop GPU


In [13]:
torch.backends.mps.is_available()

False