# 19th July 2026

In [1]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

In [2]:
import torch
data = torch.tensor([1, 2,3, 4],dtype=torch.long)
data

tensor([1, 2, 3, 4])

In [3]:
x = torch.tensor([1,2,3,4,5,9])
y = torch.tensor([2,4,6,8,10,12])
x*y

tensor([  2,   8,  18,  32,  50, 108])

In [4]:
data = torch.tensor ([[
    [1, 2, 3,4,5],
    [6, 7, 8,9,10],
    [11, 12, 13,14,15]
]])
data.ndim

3

In [5]:
data.squeeze(0)
data

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]])

In [6]:
data.T

C:\Users\barat\AppData\Local\Temp\ipykernel_20872\3511928789.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4317.)
  data.T


tensor([[[ 1],
         [ 6],
         [11]],

        [[ 2],
         [ 7],
         [12]],

        [[ 3],
         [ 8],
         [13]],

        [[ 4],
         [ 9],
         [14]],

        [[ 5],
         [10],
         [15]]])

In [7]:
A=torch.tensor([[1, 2, 3],
                [4, 5, 6]])
B=torch.tensor([[7, 8],
                [9, 10],
                [11, 12]])
A.matmul(B)

tensor([[ 58,  64],
        [139, 154]])

In [8]:
A@B

tensor([[ 58,  64],
        [139, 154]])

In [9]:
A=torch.tensor([[1, 2, 3],
                [4, 5, 6]])
A.sum(dim=0) #column wise sum

tensor([5, 7, 9])

In [10]:
A.sum(dim=1) #row wise sum

tensor([ 6, 15])

In [11]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
A= torch.tensor([[1, 2, 3],
                [4, 5, 6]])
A = A.to(device)
A.device

device(type='cpu')

In [ ]:
import seaborn as sns
import pandas as pd
from torch import nn,optim
from sklearn.metrics import accuracy_score

df = sns.load_dataset('titanic')
df.drop(["class", "embarked", "deck","alive"], axis=1, inplace=True)
df.dropna(inplace=True)
df = pd.get_dummies(df, columns=["sex", "who", "adult_male", "embark_town", "alone"], dtype="int", drop_first=True)
X=torch.tensor(df.drop("survived",axis=1).values, dtype=torch.float)
y=torch.tensor(df["survived"].values, dtype=torch.float).view(-1, 1)

class SimpleNN(nn.Module):
    def __init__(self,input,output):
        super().__init__() # Call nn.Module constructor
        self.fc1=nn.Linear(input,16) #input layer and hidden layer 1
        self.fc2=nn.Linear(16,32) # hidden layer 1 and hidden layer 2
        self.fc3=nn.Linear(32,8) # hidden layer 2 and hidden layer 3
        self.fc4=nn.Linear(8,output) # hidden layer 3 and output layer
        self.sigmoid=nn.Sigmoid() # sigmoid function
    def forward(self,X):
        X=self.fc1(X)
        X=self.fc2(X)
        X=self.fc3(X)
        X=self.fc4(X)
        X=self.sigmoid(X)
        return X
model=SimpleNN(X.shape[1],1)
criterion=nn.BCELoss()
optimizer=optim.Adam(model.parameters())
num_epochs=10000
for epoch in range(1,num_epochs+1):
    optimizer.zero_grad() # reset gradients
    pred = model(X) # Predict output from first round
    loss = criterion(pred,y) # calculate lose in a given epoch
    loss.backward() # perform backward propagation
    optimizer.step() #update weights
    output = (pred>0.5).float()
    if epoch%100==0:
        print(f"Epoch{epoch}/{num_epochs},Loss:{loss.item()},Accuracy:{accuracy_score(y,output)}")


Epoch100/10000,Loss:0.5940953493118286,Accuracy:0.6811797752808989
Epoch200/10000,Loss:0.4647851288318634,Accuracy:0.7808988764044944
Epoch300/10000,Loss:0.44093501567840576,Accuracy:0.8033707865168539
Epoch400/10000,Loss:0.4229271709918976,Accuracy:0.8188202247191011
Epoch500/10000,Loss:0.4191663861274719,Accuracy:0.8216292134831461
Epoch600/10000,Loss:0.4180515706539154,Accuracy:0.824438202247191
Epoch700/10000,Loss:0.4178588390350342,Accuracy:0.824438202247191
Epoch800/10000,Loss:0.4178239703178406,Accuracy:0.824438202247191
Epoch900/10000,Loss:0.41789835691452026,Accuracy:0.8230337078651685
Epoch1000/10000,Loss:0.4177913963794708,Accuracy:0.824438202247191
Epoch1100/10000,Loss:0.4184032380580902,Accuracy:0.824438202247191
Epoch1200/10000,Loss:0.4177696704864502,Accuracy:0.824438202247191
Epoch1300/10000,Loss:0.41783973574638367,Accuracy:0.8230337078651685
Epoch1400/10000,Loss:0.4179452061653137,Accuracy:0.8230337078651685
Epoch1500/10000,Loss:0.41806939244270325,Accuracy:0.82303370